### ISSUE TITLE
Implementing the "what we do" section and changing page spacing

### ISSUE THREAD

**Issue by alpal7327** [fortissimo-ff/fortissimo-landing-page#13]
1. What the issue is: Implementing the "what we do" section and fixing spacing on the About page. Also added alt tags to the images.

2. Why: The "what we do" section needs to be implemented and the bottom of the About page is too tight. Added alt tags in good practice.

**Comment by CookiesNCream** [comment]
Dependencies: Use of "react-infinite-scroll-component": "^4.2.0" and "smoothscroll-polyfill": "^0.4.3" enhances the user experience of visitors to the landing page.

About.js: Good to import Blurbs.js in OurStory.js, import OurStory.css in OurStory.js, and import OurStory.js in About.js to ease future additions/amendments. Please refer to WhatWeDo.js.

Blurbs.js: Thanks for the proof-reading of the American spelling of the word "cozy". 

Blurbs.js: Code is cleaner with alt in image tags and styling moved to About.css.

Contact.js: Code is clean and well-organized for future additions/amendments. The next team member can remove `//`next to each line of code and use the template by Allan.

WhatWeDo/Blurbs.js: Code is clean and use of alt in image tags, with styling in What.css. 

WhatWeDo.js: Code is clean and well-organized for future additions/amendments. Please do the same for OurStory.js by making updates to About.js and creating OurStory.js. 

About.css: Good styling of elements, spacing between the cliparts and blurbs, and presentation of each clipart. `#Title` can include `font-style: italic;` and `font-weight: lighter;` for uniform format as the WhatWeDo section of the About page and `#Header` on the Contact page.

Contact.css: Code is clean and well-organized for future additions/amendments. 

Home.css: Good use of `position: relative;` to be uniform with the Contact page.

What.css: Code is clean and well-organized for future additions/amendments.
