### ISSUE TITLE
Implementing the Contact Page

### ISSUE THREAD

**Issue by aliceviera** [fortissimo-ff/fortissimo-landing-page#15]
What: I will begin implementing the Contact page.

Why: The Contact page is necessary for users to be able to communicate with Fortissimo's social media pages and feel connected to our company.

**Comment by CookiesNCream** [comment]
App.js: Code is clean and well-organized for future additions/amendments.

Chat.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Contact.js: Code is clean and well-organized for future additions/amendments. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? Any particular reason for the change from `import Header from './Header.js';` etc. to `import Header from "./Header.js";` etc.?

Copyright.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Follow.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Header.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Help.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`?

SocialMediaIcons.js: Code is clean, clearly presented, and well-organized for future additions/amendments. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? Any particular reason for the change to `import Facebook_logo from "../../img/img-icon-Facebook.svg";`, `import Instagram_logo from "../../img/img-icon-Instagram.svg";`, and `import Twitter_logo from "../../img/img-icon-Twitter.svg";`?

Chat.js: [https://m.me/breakfasy](url) needs to replace [m.me/breakfasy](url) in the code for Messenger to be displayed to visitors of our landing page.
