### ISSUE TITLE
Editting styling of elements 

### ISSUE THREAD

**Issue by DustinCai** [fortissimo-ff/fortissimo-landing-page#17]
What the issue is: Styling of cliparts on landing page. 

Why it is an issue: For better aesthetics on landing page.

**Comment by CookiesNCream** [comment]
About/Blurbs.js: Code is clean. Good use of LeftCircleDiv, RightCircleDiv to hold images and fillLeftBlurbImages, fillRightBlurbImages to present images.

WhatWeDo/Blurbs.js: Code is clean. Good use of `id = "wwdLeftBlurb"` and  `id = "wwdRightBlurb"` to present the images.

About.css: Code is clean and good tweaking of class attributes to reflect element styling.

What.css: Code is clean. Good tweaking of class and id attributes to reflect element styling.

Code eases future additions/amendments.
