### ISSUE TITLE
Adapting the page for different resolutions

### ISSUE THREAD

**Issue by drewrip** [fortissimo-ff/fortissimo-landing-page#20]
What: Creating solutions so that when the page is viewed on mobile, the various components do not interfere with each other.

Why: To improve the user experience. In many mobile resolutions, where they are taller than wider, elements tend to render on top of each other making them unreadable.

#19

**Comment by CookiesNCream** [comment]
WhatWeDo/Blurb.js: Code is clean. Good use of margin and div id.

About.css: Good use of padding and removal of height.

App.css: Code is clean and good use of flex for auto-resizing.

Contact.css: Code is clean and good use of @media queries to cater to different devices with different resolutions.

Home.css: Code is clean and good use of @media queries to cater to different devices with different resolutions.

NavBar.css: Good formatting of elements.

Video.css: Good use of height.

What.css: Code is clean. Good use of @media queries to cater to different devices with different resolutions, flex for auto-resizing, and removal of height.

**Comment by CookiesNCream** [comment]
### Outstanding Amendments

_**More Important**_

There are @media queries in Home.css, Contact.css, What.css, but not About.css.
While there are no compile errors when tested in the development server, the elements on the OurStory section and the WhatWeDo section are not aligned properly. Tested on 1920 X 1080, 1680 X 1050, 1600 X 900, 1440 X 900, 1400 X 1050.

_The font size of "Our Story" and "What We Do" is much smaller than "Contact Us"._
About.css, What.css, Contact.css

_The titles "Our Story" and "What We Do" are not of the same font size, font style, and font weight._
About.css:  `#Title` can include `font-style: italic;` and `font-weight: lighter;` for uniform format as the WhatWeDo section of the About page and `#Header` on the Contact page.

_**Less Important**_

About.js: Good to import Blurbs.js in OurStory.js, import OurStory.css in OurStory.js, and import OurStory.js in About.js to ease future additions/amendments. Please refer to WhatWeDo.js.

WhatWeDo.js: Code is clean and well-organized for future additions/amendments. Please do the same for OurStory.js by making updates to About.js and creating OurStory.js.

**_Miscellanous_**

Chat.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Contact.js: Code is clean and well-organized for future additions/amendments. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? Any particular reason for the change from `import Header from './Header.js';` etc. to `import Header from "./Header.js";` etc.?

Copyright.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Follow.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Header.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? 

Help.js: Code is clean and clearly presented. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`?

SocialMediaIcons.js: Code is clean, clearly presented, and well-organized for future additions/amendments. Any particular reason for the change from `import React, { Component } from 'react';` to `import React, { Component } from "react";`? Any particular reason for the change to `import Facebook_logo from "../../img/img-icon-Facebook.svg";`, `import Instagram_logo from "../../img/img-icon-Instagram.svg";`, and `import Twitter_logo from "../../img/img-icon-Twitter.svg";`?
