### ISSUE TITLE
Outstanding Amendments from Pull Request #19

### ISSUE THREAD

**Issue by moojink** [fortissimo-ff/fortissimo-landing-page#21]
Fixing most of the issues listed by Linda in Pull Request #19.

**Comment by CookiesNCream** [comment]
About/About.js: Code is clean and well-organized for future additions/amendments by incorporating the OurStory component.

About/Blurbs.js: Code is clean, good use of `<div className = "BlurbContainer">`  and `<h3 className = "BlurbText">`  to align the blurbs and text, good positioning of left/right images to display based on design, and such formatting eases future additions/amendments.

About/OurStory.js: Code is clean and creating OurStory.js improves organization of components for future additions/amendments.

WhatWeDo/Blurbs.js: Code is clean, good use of `<div className = "BlurbContainer">`  and `<h3 className = "BlurbText">`  to align the blurbs and text, good positioning of left/right images to display based on design, and such formatting eases future additions/amendments.

**About.css**: Code is clean, good incorporation of common class properties for OurStory.css and What.css, and well-organized for future additions/amendments. **Is there any reason the `.RightBlurbImages` class is declared 2 times?**

OurStory.css: Code is clean, good incorporation of class properties for OurStory.css, and well-organized for future additions/amendments.

**What.css**: Code is clean, good incorporation of class properties for What.css, and well-organized for future additions/amendments. **Is `@media (max-width: 1800px) and (min-width: 751px)` meant to be `@media (max-width: 900px) and (min-width: 751px)`?**
