### ISSUE TITLE
CSS tweaks & link

### ISSUE THREAD

**Issue by DustinCai** [fortissimo-ff/fortissimo-landing-page#24]
What: Removed class duplicates, tweaked media width, and added correct messenger link. 

Why: Better code organization, screen sizing, and attracting consumers to the appropriate link.

**Comment by CookiesNCream** [comment]
Contact/Chat.js: Messenger link updated to allow for interaction with potential customers.

About.css: Combination of two `.RightBlurbImages` improves organization of code for future additions/amendments. There were two `width: 80px;`, but one of them has been removed.

What.css: The `@media (max-width: 900px) and (min-width: 751px)` is reflected to allow devices with such a resolution to be displayed on the screens.
