### ISSUE TITLE
Implementing the Our Story page as well as home page tweaks

### ISSUE THREAD

**Issue by bradhchen** [fortissimo-ff/fortissimo-landing-page#3]
What is the issue: The Our Story page must be implemented. In addition, the positioning of elements like the "Learn More" button and the slogan need to be adjusted and the link to instagram provided. 

Why is it an issue: The positioning of elements on the home screen should be adjusted in order to look better aesthetically.

**Comment by CookiesNCream** [comment]
The conflicts are too complex to be resolved using the web editor.

Do make a working copy of the code changes you have made for your pull request (Our Story) first.

Can you please get the latest update from the master of our landing page repo by updating your forked repo in your GitHub account and your cloned forked repo in your computer before making the code changes in your computer and pushing them back to your forked repo in your GitHub account followed by a new issue/pull request?
