### ISSUE TITLE
Implementing video page

### ISSUE THREAD

**Issue by bradhchen** [fortissimo-ff/fortissimo-landing-page#9]
What the issue is: Video must be included into the website. In addition Linda left feedback on the last merge to improve styling and file management.

Why is it an issue: Video must be included in order to introduce users to fortissimo. Also, styling and file management must be improved in order for future developers to easily make improvements.

What needs improvement: See "What the issue is"

What can be done to fix it: Use an external React component to implement videos.

**Comment by CookiesNCream** [comment]
It is good practice to include alt={alternate text of image} in image tags (Blurbs.js).

While the Blurbs.js works with most of the styling moved to About.css, it would also be good practice if <img className = "LeftBlurbImages" src={require("../../img/img-clipart-os-coffee.png")} style = {{backgroundColor: "white"}}/ > and <h3 className = "Blurbs" style = {{fontSize: "22pt"}}> are moved to About.css .

The fortissimo video URL is https://youtu.be/79XsGVCmNCo
Please use the URL.
